#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build x86_64 OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 0,1,3,5
#  watch:
#    types: started

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-18.06-k5.4
  CONFIG_FILE: config/x86/x86_64-openwrt-target.config
  DIY_SH: scripts/project-openwrt.sh
  WEBROOT: /data/dnmp/www/openwrt.cc
  RUNNER: project-x86_64

jobs:
  Toolchain:
    runs-on: project-x86_64

    outputs:
      TOOLCHAIN_STATUS: ${{ steps.toolchain.outputs.TOOLCHAIN_STATUS }}

    steps:
      - name: Umount Missing Loop Devices
        id: umount
        run: |
          sudo umount /dev/loop*p1 || true
          sudo losetup -D || true
          lsblk

      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo umount /dev/loop*p1 || true
          sudo losetup -D || true
          rm -rf openwrt.img
          fallocate -l 150G openwrt.img
          echo 'type=83' | sfdisk openwrt.img
          export LOOP="$(sudo losetup -f -P --show openwrt.img)"
          echo "LOOP=$LOOP" >> $GITHUB_ENV
          echo "::set-output name=LOOP::$(echo $LOOP)"
          sudo mkfs.ext4 ${LOOP}p1
          mkdir openwrt
          sudo mount ${LOOP}p1 openwrt
          lsblk
          sudo chown -R suling:suling openwrt
          cd openwrt
          echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV

      - name: Clone Source Code
        id: clone
        run: |
          df -hT $PWD
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH
          mv immortalwrt/* openwrt
          mv immortalwrt/.git* openwrt

      - name: Update Feeds
        id: update
        run: |
          cd $OPENWRTROOT
          ./scripts/feeds update -a

      - name: Install Feeds
        id: install
        run: |
          cd $OPENWRTROOT
          ./scripts/feeds install -a

      - name: Load Custom Configuration
        run: |
          [ -e files ] && mv files $OPENWRTROOT/files
          cd $OPENWRTROOT
          chmod +x ../scripts/*.sh
          ../$DIY_SH
          ../scripts/preset-clash-core.sh amd64
          ../scripts/preset-terminal-tools.sh

      - name: Download All Packages
        id: download
        run: |
          cd $OPENWRTROOT
          wget -q https://raw.githubusercontent.com/openwrt/openwrt/master/scripts/download.pl -O scripts/download.pl
          rm -rf dl
          cp -r /data/cache/dl .
          echo "CONFIG_ALL=y" >> .config
          make defconfig
          make download -j16 IGNORE_ERRORS=1
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile Tools
        id: tools
        run: |
          rm -f $OPENWRTROOT/.config*
          cp $CONFIG_FILE $OPENWRTROOT/.config
          cat config/firmware-extra.config >> $OPENWRTROOT/.config
          cat config/extra-wireless-support.config >> $OPENWRTROOT/.config
          cd $OPENWRTROOT
          make defconfig
          echo -e "$(nproc) threads compile"
          make tools/install -j$(nproc) BUILD_LOG=1 || make tools/install -j1 V=s

      - name: Compile Toolchain
        id: toolchain
        run: |
          cd $OPENWRTROOT
          echo -e "$(nproc) threads compile"
          make toolchain/compile -j$(nproc) BUILD_LOG=1 || make toolchain/compile -j1 V=s
          echo "::set-output name=TOOLCHAIN_STATUS::success"

      - name: Collect Logs
        id: toolchain-logs-collect
        if: always()
        run: |
          cd $OPENWRTROOT
          mkdir -p output/logs
          mv logs output/logs/${{ github.job }}

      - name: Upload Logs
        id: toolchain-logs-upload
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: Logs-${{ github.job }}
          path: openwrt/output/logs/${{ github.job }}

      - name: Prepare Disk Image
        id: prepare
        if: always()
        run: |
          sync
          sudo umount ${LOOP}p1 || true
          sudo losetup -d $LOOP || true
          lsblk
          mkdir -p /data/disk/$RUNNER
          mv openwrt.img /data/disk/$RUNNER

  Firmware:
    if: needs.Toolchain.outputs.TOOLCHAIN_STATUS == 'success'
    needs: [Toolchain]
    runs-on: project-x86_64

    outputs:
      PLATFORM: ${{ steps.compile.outputs.PLATFORM }}
      TARGET: ${{ steps.compile.outputs.TARGET }}
      SUBTARGET: ${{ steps.compile.outputs.SUBTARGET }}
      GENERATE_STATUS: ${{ steps.generate.outputs.GENERATE_STATUS }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        id: init
        run: |
          mv /data/disk/$RUNNER/openwrt.img .
          export LOOP="$(sudo losetup -f -P --show openwrt.img)"
          echo "LOOP=$LOOP" >> $GITHUB_ENV
          echo "::set-output name=LOOP::$(echo $LOOP)"
          mkdir openwrt
          sudo mount ${LOOP}p1 openwrt
          lsblk
          sudo chown -R suling:suling openwrt
          cd openwrt
          echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV

      - name: Compile Firmware Packages
        id: compile
        timeout-minutes: 330
        run: |
          cd $OPENWRTROOT
          echo -e "$(nproc) threads compile"
          make target/compile -j$(nproc) BUILD_LOG=1 || make target/compile -j1 V=s IGNORE_ERRORS=1
          make diffconfig
          make package/compile -j$(nproc) BUILD_LOG=1 || make package/compile -j$(nproc) || make package/compile -j1 V=s
          make package/index
          cd $OPENWRTROOT/bin/packages/*
          PLATFORM=$(basename `pwd`)
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
          echo "::set-output name=PLATFORM::$(echo $PLATFORM)"
          cd $OPENWRTROOT/bin/targets/*
          TARGET=$(basename `pwd`)
          echo "TARGET=$TARGET" >> $GITHUB_ENV
          echo "::set-output name=TARGET::$(echo $TARGET)"
          cd *
          SUBTARGET=$(basename `pwd`)
          echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV
          echo "::set-output name=SUBTARGET::$(echo $SUBTARGET)"
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=FIRMWARE::$(echo $PWD)"
          echo "::set-output name=COMPILE_STATUS::success"

      - name: Generate Firmware
        if: steps.compile.outputs.COMPILE_STATUS == 'success'
        id: generate
        run: |
          cd data/opkg
          sed -i "s/subtarget/$SUBTARGET/g" distfeeds.conf
          sed -i "s/target\//$TARGET\//g" distfeeds.conf
          sed -i "s/platform/$PLATFORM/g" distfeeds.conf
          cd $OPENWRTROOT
          mkdir -p files/etc/opkg
          cp ../data/opkg/distfeeds.conf files/etc/opkg/distfeeds.conf
          mkdir -p files/www/snapshots
          cp -r bin/targets files/www/snapshots
          mkdir -p files/etc/uci-defaults/
          cp ../scripts/init-settings.sh files/etc/uci-defaults/99-init-settings
          mkdir -p files/bin
          cp ../scripts/ipv6-helper.sh files/bin/ipv6-helper
          make package/install || make package/install -j1 V=s
          make target/install || make target/install -j1 V=s
          make checksum
          cd $FIRMWARE
          gzip *esxi-flat.vmdk
          mkdir -p $OPENWRTROOT/output/bin/targets/$TARGET
          cp -r $FIRMWARE $OPENWRTROOT/output/bin/targets/$TARGET
          echo "::set-output name=GENERATE_STATUS::success"

      - name: Collect Logs
        id: firmware-logs-collect
        if: always()
        run: |
          cd $OPENWRTROOT
          mv logs output/logs/${{ github.job }}

      - name: Upload Logs
        id: firmware-logs-upload
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: Logs-${{ github.job }}
          path: openwrt/output/logs/${{ github.job }}

      - name: Prepare Disk Image
        if: always()
        id: prepare
        run: |
          sync
          sudo umount ${LOOP}p1 || true
          sudo losetup -d $LOOP || true
          lsblk
          mkdir -p /data/disk/$RUNNER
          mv openwrt.img /data/disk/$RUNNER

  Extra-Packages:
    if: needs.Firmware.outputs.GENERATE_STATUS == 'success'
    needs: [Firmware]
    runs-on: project-x86_64

    outputs:
      COMPILE_STATUS: ${{ steps.compile.outputs.COMPILE_STATUS }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Restore Variables
        id: restore
        run: |
          echo "PLATFORM=$(echo '${{needs.Firmware.outputs.PLATFORM}}')" >> $GITHUB_ENV
          echo "TARGET=$(echo '${{needs.Firmware.outputs.TARGET}}')" >> $GITHUB_ENV
          echo "SUBTARGET=$(echo '${{needs.Firmware.outputs.SUBTARGET}}')" >> $GITHUB_ENV

      - name: Initialization Environment
        id: init
        run: |
          mv /data/disk/$RUNNER/openwrt.img .
          export LOOP="$(sudo losetup -f -P --show openwrt.img)"
          echo "LOOP=$LOOP" >> $GITHUB_ENV
          echo "::set-output name=LOOP::$(echo $LOOP)"
          mkdir openwrt
          sudo mount ${LOOP}p1 openwrt
          lsblk
          sudo chown -R suling:suling openwrt
          cd openwrt
          echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV

      - name: Compile Extra Packages
        id: compile
        timeout-minutes: 330
        run: |
          cd $OPENWRTROOT
          rm -f .config*
          cp ../$CONFIG_FILE ./.config
          cat ../config/packages-extra.config >> $OPENWRTROOT/.config
          make defconfig
          make diffconfig
          make package/compile -j$(nproc) BUILD_LOG=1 IGNORE_ERRORS="y m n" || make package/compile -j1 V=s IGNORE_ERRORS="y m n"
          make package/index
          mkdir -p $OPENWRTROOT/output/bin/packages
          cp -r bin/packages/$PLATFORM $OPENWRTROOT/output/bin/packages
          echo "::set-output name=COMPILE_STATUS::success"

      - name: Collect Logs
        id: packages-logs-collect
        if: always()
        run: |
          cd $OPENWRTROOT
          mv logs output/logs/${{ github.job }}
          cp -r output/logs output/bin/targets/$TARGET/$SUBTARGET

      - name: Compress Bin Folder
        if: steps.compile.outputs.COMPILE_STATUS == 'success'
        id: compress
        run: |
          cd $OPENWRTROOT/output
          zip -q -s 500m -r bin-archive.zip bin
          rm -rf bin

      - name: Upload Bin Archive
        id: upload
        uses: actions/upload-artifact@main
        with:
          name: Bin-Archive
          path: openwrt/output

      - name: Upload Logs
        id: packages-logs-upload
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: Logs-${{ github.job }}
          path: openwrt/output/logs/${{ github.job }}

      - name: Prepare Disk Image
        if: always()
        id: prepare
        run: |
          sync
          sudo umount ${LOOP}p1 || true
          sudo losetup -d $LOOP || true
          lsblk
          mkdir -p /data/disk/$RUNNER
          mv openwrt.img /data/disk/$RUNNER

  Upload:
    if: needs.Extra-Packages.outputs.COMPILE_STATUS == 'success'
    needs: [Extra-Packages, Firmware]
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Restore Variables
        id: restore
        run: |
          echo "PLATFORM=$(echo '${{needs.Firmware.outputs.PLATFORM}}')" >> $GITHUB_ENV
          echo "TARGET=$(echo '${{needs.Firmware.outputs.TARGET}}')" >> $GITHUB_ENV
          echo "SUBTARGET=$(echo '${{needs.Firmware.outputs.SUBTARGET}}')" >> $GITHUB_ENV

      - name: Download Bin Archive
        id: download
        uses: actions/download-artifact@v2
        with:
          name: Bin-Archive
          path: openwrt

      - name: Decompress Bin Folder
        id: decompress
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          cd openwrt
          echo "OPENWRTROOT=$PWD" >> $GITHUB_ENV
          zip -q -s 0 bin-archive.zip --out bin.zip
          unzip bin.zip
          cd bin/targets/$TARGET/$SUBTARGET
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Deploy Files To Server
        id: server
        env:
          HOST: "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_IP }}"
          SOURCE_TARGETS: "openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/"
          SOURCE_PACKAGES: "openwrt/bin/packages/${{ env.PLATFORM }}/"
          DEST_TARGETS: "${{ env.WEBROOT }}/snapshots/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/"
          DEST_PACKAGES: "${{ env.WEBROOT }}/snapshots/packages/${{ env.PLATFORM }}/"
          REMOTE_PRIVATEKEY: "${{secrets.REMOTE_PRIVATEKEY}}"
        if: env.REMOTE_PRIVATEKEY != null
        run: |
          mkdir -p ~/.ssh/
          install -m 600 /dev/null ~/.ssh/id_rsa
          echo "${{secrets.REMOTE_PRIVATEKEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -q -t -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $HOST \
          bash -c "'mkdir -p $WEBROOT/snapshots/targets/$TARGET/$SUBTARGET \
          $WEBROOT/snapshots/packages/$PLATFORM'"
          rsync -chavP --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" $SOURCE_TARGETS $HOST:$DEST_TARGETS
          rsync -chavP --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" $SOURCE_PACKAGES $HOST:$DEST_PACKAGES
          bash -c "'mkdir -p $WEBROOT/archive/$(date +%Y)/$(date +%m)/$(date +%d)/snapshots/targets/$TARGET && \
          mkdir -p $WEBROOT/archive/$(date +%Y)/$(date +%m)/$(date +%d)/snapshots/packages'"
          rsync -axv --delete $WEBROOT/snapshots/targets/$TARGET/$SUBTARGET $WEBROOT/archive/$(date +%Y)/$(date +%m)/$(date +%d)/snapshots/targets/$TARGET
          rsync -axv --delete $WEBROOT/snapshots/packages/$PLATFORM $WEBROOT/archive/$(date +%Y)/$(date +%m)/$(date +%d)/snapshots/packages
          echo "::warning file=Firmware-OpenWrt.cc::Download Link: https://openwrt.cc/snapshots/targets/$TARGET/$SUBTARGET"
